### ISSUE TITLE
建议作者把一些工具的作用也写上去

### ISSUE THREAD

**Issue by benyVip** [judasn/Linux-Tutorial#22]
比如FTP，可能新手完全不了解FTP的作用是啥~一上来就是怎么配置有点困惑

**Comment by wanlum** [comment]
but I think not very necessary

**Comment by judasn** [comment]
工具的作用，我是认为大家可以自己 google，或者一般文章我都给了官网链接了，直接到官网自己看也行。
这个系列定位还是工具书。
