### ISSUE TITLE
5.7.11版本 cmake的时候会爆   error COULD_NOT_FIND_BOOST

### ISSUE THREAD

**Issue by zhangdihong** [judasn/Linux-Tutorial#6]

**Comment by judasn** [comment]
Mysql 5.7.11 的环境我还没试过，但是不排除编译方式改变了。

**Comment by zhangdihong** [comment]
http://www.2cto.com/database/201510/447675.html   原来是需要一个库今天重新试了下 能成功了

**Comment by oh1h0ney** [comment]
error COULD_NOT_FIND_BOOST 是没有 boost 库，在 cmake 参数后面加 -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/usr/local/boost 就正常了。这个参数会自动下载 boost 并将其放在 /usr/local/boost。
修改后的参数应该是
cmake -DCMAKE_INSTALL_PREFIX=/usr/program/mysql -DMYSQL_DATADIR=/usr/program/mysql/data -DMYSQL_UNIX_ADDR=/tmp/mysql.sock -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DWITH_EXTRA_CHARSETS:STRING=utf8 -DWITH_MYISAM_STORAGE_ENGINE=1 -DWITH_INNOBASE_STORAGE_ENGINE=1 -DENABLED_LOCAL_INFILE=1 -DDOWNLOAD_BOOST=1 -DWITH_BOOST=/usr/local/boost

**Comment by judasn** [comment]
我上次编译安装了，确实发现有这个问题，需要 boost 库。
但是实际上，目前我们基本都用 docker 部署了，所以很多时候这些都不重要了~

但是，还是要感谢反馈~
